name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Get latest mcmeta commit hash
      uses: octokit/request-action@v2.x
      id: get_mcmeta_hash
      with:
        route: GET /repos/misode/mcmeta/branches/summary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        npm install
        export mcmeta_hash="'${{ fromJson(steps.get_mcmeta_hash.outputs.data).commit.sha }}'"
        npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
